33846378 Upgrade cups to 2.4.1

diff --git a/components/cups/patches/01-test-port.patch b/components/cups/patches/01-test-port.patch
--- a/components/cups/patches/01-test-port.patch
+++ b/components/cups/patches/01-test-port.patch
@@ -7,12 +7,36 @@ Install trap to kill leftover cupsd.
 
 Restart test if cupsd fails to start.
 
+Expect more warning message because of specific `pdftops-renderer' setting.
+
 This patch is not for upstream. The change was made to make the tests more
 reliable in Userland infrastructure.
 
---- a/test/run-stp-tests.sh	2020-10-12 11:58:22.243548554 +0200
-+++ b/test/run-stp-tests.sh	2020-10-12 12:00:04.366936122 +0200
-@@ -179,7 +179,12 @@
+--- a/Makefile
++++ b/Makefile
+@@ -240,16 +240,16 @@ #
+ 
+ testserver:	all unittests
+ 	echo Running CUPS test server...
+-	cd test; ./run-stp-tests.sh $(TESTOPTIONS)
++	cd test; while ./run-stp-tests.sh $(TESTOPTIONS); [ $$? -eq 2 ]; do :; done
+ 
+ 
+ check test:	all unittests
+ 	echo Running CUPS test suite...
+-	cd test; ./run-stp-tests.sh 1 0 n n
++	cd test; while ./run-stp-tests.sh 1 0 n n; [ $$? -eq 2 ]; do :; done
+ 
+ debugcheck debugtest:	all unittests
+ 	echo Running CUPS test suite with debug printfs...
+-	cd test; ./run-stp-tests.sh 1 0 n y
++	cd test; while ./run-stp-tests.sh 1 0 n y; [ $$? -eq 2 ]; do :; done
+ 
+ 
+ #
+--- a/test/run-stp-tests.sh
++++ b/test/run-stp-tests.sh
+@@ -180,7 +180,12 @@
  	fi
  fi
  
@@ -26,7 +50,7 @@ reliable in Userland infrastructure.
  cwd=`pwd`
  root=`dirname $cwd`
  CUPS_TESTROOT="$root"; export CUPS_TESTROOT
-@@ -596,9 +601,6 @@
+@@ -594,9 +599,6 @@
  	fi
  
  	LD_PRELOAD="$root/cups/libcups.so.2:$root/cups/libcupsimage.so.2"
@@ -36,7 +60,7 @@ reliable in Userland infrastructure.
  fi
  
  if test -f "$root/cups/libcups.2.dylib"; then
-@@ -681,6 +683,7 @@
+@@ -679,6 +681,7 @@
  $runcups $VALGRIND ../scheduler/cupsd -c $BASE/cupsd.conf -f >$BASE/log/debug_log 2>&1 &
  
  cupsd=$!
@@ -44,7 +68,7 @@ reliable in Userland infrastructure.
  
  if test "x$testtype" = x0; then
  	# Not running tests...
-@@ -698,8 +701,8 @@
+@@ -696,8 +699,8 @@
  	echo $ac_n "Press ENTER to continue... $ac_c"
  	read junk
  else
@@ -54,8 +78,8 @@ reliable in Userland infrastructure.
 +	sleep 5
  fi
  
- while true; do
-@@ -708,8 +711,8 @@
+ tries=0
+@@ -707,8 +710,8 @@
  		break
  	fi
  
@@ -63,17 +87,20 @@ reliable in Userland infrastructure.
 -	sleep 10
 +	echo "Cupsd is not ready after 5 seconds. Port in use? Terminating with 2 to try again."
 +	exit 2
+ 
+ 	tries=`expr $tries + 1`
  done
+@@ -1134,10 +1137,10 @@
  
- #
---- a/Makefile	2020-04-27 20:04:29.000000000 +0200
-+++ b/Makefile	2020-10-13 12:26:24.922379349 +0200
-@@ -237,7 +237,7 @@
- 
- check:	all unittests
- 	echo Running CUPS test suite with defaults...
--	cd test; ./run-stp-tests.sh 1 0 n n
-+	cd test; while ./run-stp-tests.sh 1 0 n n; [ $$? -eq 2 ]; do :; done
- 
- debugcheck:	all unittests
- 	echo Running CUPS test suite with debug printfs...
+ # Warning log messages
+ count=`$GREP '^W ' $BASE/log/error_log | $GREP -v CreateProfile | $GREP -v 'libusb error' | $GREP -v ColorManager | $GREP -v 'Avahi client failed' | wc -l | awk '{print $1}'`
+-if test $count != 14; then
+-	echo "FAIL: $count warning messages, expected 14."
++if test $count != 80; then
++	echo "FAIL: $count warning messages, expected 80."
+ 	$GREP '^W ' $BASE/log/error_log
+-	echo "    <p>FAIL: $count warning messages, expected 14.</p>" >>$strfile
++	echo "    <p>FAIL: $count warning messages, expected 80.</p>" >>$strfile
+ 	echo "    <pre>" >>$strfile
+ 	$GREP '^W ' $BASE/log/error_log | sed -e '1,$s/&/&amp;/g' -e '1,$s/</&lt;/g' >>$strfile
+ 	echo "    </pre>" >>$strfile
